### ISSUE TITLE
Note Force SSL

### ISSUE THREAD

**Issue by csaeum** [Globulopolis/Counter#16]
Note Force SSL

I run Matomo in Docker with Traefik as a proxy.
This means that Matomo runs even without SSL.

But Traefik translates this to https. It runs stably and without any problems.

Unfortunately, your plugin checks the server and so the JS is delivered with HTTP

What causes mixed content and the JS is not executed.

I am not a programmer and have simply changed the http to https in the API.php. So it works for me now.

I would think it would be a good idea if your plugin could be used in one of the next updates
```
[General]
force_ssl = 1
```

or reacts to the ForceSSL plugin and then only delivers https

Alternative due to more and more https pages just deliver HTTPS.

Thanks for the plugin and greetings

**Comment by Globulopolis** [comment]
Closed via https://github.com/Globulopolis/Counter/commit/b5005d42e1ac120e913c9562e8420e5c0896b9db

**Comment by Globulopolis** [comment]
@csaeum please test new version in you setup and let me know if any issues still exists.

**Comment by csaeum** [comment]
@Globulopolis 
I once transferred the commit to my API.php.
it works and it is taken with https.

Thank you for your fast reaction!
