### ISSUE TITLE
Sequence 'piwik_archive_numeric_2015_01' not found.

### ISSUE THREAD

**Issue by amq** [Globulopolis/Counter#6]
When I select 'day' or 'yesterday' I get this this error.

The url I'm using:
```
index.php?module=Counter&action=show&date=day&id=2
```

**Comment by Globulopolis** [comment]
Very strange.
Look at the DB. Do you see a `piwik_archive_numeric_2015_01` table?

**Comment by Globulopolis** [comment]
See https://github.com/piwik/piwik/issues/6929
