### ISSUE TITLE
Установка стартового значения для счетчика PIWIK

### ISSUE THREAD

**Issue by lemira** [Globulopolis/Counter#8]
А трудно вам было бы ввести такой параметр?
Вы же картинку формируете, ну и прибавили бы число )).
Это к "накрутке" счетчика никакого отношения не имеет - все равно, тот, кто захочет накрутить, возьмет счетчик с установкой начального числа, и никакой пивик ему не нужен.

Не одному мне, наверняка, нужно.

Удачи вам!

**Comment by Globulopolis** [comment]
Closed via bd33e67bac5d6acaac4b63741cd697927b726375
